global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservice-1'
    static_configs:
      - targets: ['t1:8081']
        labels:
          service: 'AdminService'

  - job_name: 'microservice-2'
    static_configs:
      - targets: ['t23:8082']
        labels:
          service: 'UserService'

  - job_name: 'microservice-5'
    static_configs:
      - targets: ['t5:8085']
        labels:
          service: 'GameEngine'
  
  - job_name: 'microservice-7'
    static_configs:
      - targets: ['t7:8087']
        labels:
          service: 'Compile_Randoop'

  - job_name: 'microservice-8'
    static_configs:
      - targets: ['t7:8087']
        labels:
          service: 'Compile_EvoSuite'